### ISSUE TITLE
Does not work for Apple Silicon.

### ISSUE THREAD

**Issue by gachikuku** [AlexandruGG/rusty-pong#1]
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/11743804/187986870-4cdfdea7-a507-41cb-978c-7e1ea2ec5ff0.png">

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/11743804/187987079-85e11422-623c-48b2-9b57-3f5cdba96eff.png">

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/11743804/187987127-572dbb9d-2b55-434f-a952-b2153d8d64d6.png">

How can I make it work for my mac m1 laptop?

Thank you.

**Comment by AlexandruGG** [comment]
Hey @hubas0n! 👋 

Thanks for raising this; I did some further testing and I got it working on an M1 mac. While I won't update the project anymore to support this via the install script, here's the only thing you need to do to compile it -> Homebrew now installs packages (like `sdl2` in this case) in a different path, so make sure you have this in your shell profile:

```shell
export LIBRARY_PATH="$LIBRARY_PATH:/opt/homebrew/lib"
```

This will allow you to compile and build the executable. You can read more about this Homebrew change here: https://earthly.dev/blog/homebrew-on-m1/.

If you're so inclined I'm sure the Tetra folks would appreciate it if you raised this so that their [Mac-specific documentation](https://tetra.seventeencups.net/installation#mac) is updated accordingly.

**Comment by gachikuku** [comment]
Thank you @AlexandruGG  worked perfectly!

`export LIBRARY_PATH="$LIBRARY_PATH:/opt/homebrew/lib"`
 and `cargo run` done the trick.
